local guild_authority={
[1] = {ID=1,rank=1,rank_name_edit=0,guild_flag_edit=0,shorter_edit=0,league_name_edit=0,guild_dismiss=0,leader_change=0,kick_out=0,campaign_edit=0,recruit_edit=0,guild_invite=0,guild_notice=0,guild_language=0,item_buy=0,tech_reserch=0,event_open=0,message_block=0,rank_reduce=0,rank_promote=0,guild_quit=1,authority=1,help=1,resource_help=1,member_check=1,mail=1,leader_replace=0,sets_change=0,guild_set=0,guild_rank_check=1,other_guild_check=1},
[2] = {ID=2,rank=2,rank_name_edit=0,guild_flag_edit=0,shorter_edit=0,league_name_edit=0,guild_dismiss=0,leader_change=0,kick_out=0,campaign_edit=0,recruit_edit=0,guild_invite=0,guild_notice=0,guild_language=0,item_buy=0,tech_reserch=0,event_open=0,message_block=0,rank_reduce=0,rank_promote=0,guild_quit=1,authority=1,help=1,resource_help=1,member_check=1,mail=1,leader_replace=0,sets_change=0,guild_set=0,guild_rank_check=1,other_guild_check=1},
[3] = {ID=3,rank=3,rank_name_edit=0,guild_flag_edit=0,shorter_edit=0,league_name_edit=0,guild_dismiss=0,leader_change=0,kick_out=0,campaign_edit=0,recruit_edit=0,guild_invite=0,guild_notice=0,guild_language=0,item_buy=0,tech_reserch=0,event_open=0,message_block=0,rank_reduce=1,rank_promote=1,guild_quit=1,authority=1,help=1,resource_help=1,member_check=1,mail=1,leader_replace=1,sets_change=0,guild_set=0,guild_rank_check=1,other_guild_check=1},
[4] = {ID=4,rank=4,rank_name_edit=0,guild_flag_edit=0,shorter_edit=0,league_name_edit=0,guild_dismiss=0,leader_change=0,kick_out=1,campaign_edit=1,recruit_edit=1,guild_invite=1,guild_notice=1,guild_language=1,item_buy=1,tech_reserch=1,event_open=1,message_block=1,rank_reduce=1,rank_promote=1,guild_quit=1,authority=1,help=1,resource_help=1,member_check=1,mail=1,leader_replace=1,sets_change=0,guild_set=1,guild_rank_check=1,other_guild_check=1},
[5] = {ID=5,rank=5,rank_name_edit=1,guild_flag_edit=1,shorter_edit=1,league_name_edit=1,guild_dismiss=1,leader_change=1,kick_out=1,campaign_edit=1,recruit_edit=1,guild_invite=1,guild_notice=1,guild_language=1,item_buy=1,tech_reserch=1,event_open=1,message_block=1,rank_reduce=1,rank_promote=1,guild_quit=0,authority=1,help=1,resource_help=1,member_check=1,mail=1,leader_replace=0,sets_change=1,guild_set=1,guild_rank_check=1,other_guild_check=1},
[6] = {ID=6,rank=0,rank_name_edit=0,guild_flag_edit=0,shorter_edit=0,league_name_edit=0,guild_dismiss=0,leader_change=0,kick_out=0,campaign_edit=0,recruit_edit=0,guild_invite=0,guild_notice=0,guild_language=0,item_buy=0,tech_reserch=0,event_open=0,message_block=0,rank_reduce=0,rank_promote=0,guild_quit=0,authority=0,help=0,resource_help=0,member_check=0,mail=1,leader_replace=0,sets_change=0,guild_set=0,guild_rank_check=0,other_guild_check=0}
}
return guild_authority
